### ISSUE TITLE
build_linux.sh not working

### ISSUE THREAD

**Issue by TuxCoder** [routerkeygen/routerkeygenPC#10] opened 2014-10-16 16:58 UTC
the build_linux.sh script is not working on my system. (I use Debian Sid)

At first i need to change the README.md filename to README

after that the output from the build_linux.sh is:

    Build type set to 'Release'
    -- Version: 1.1.0
    CMake Warning (dev) at CMakeLists.txt:43 (project):
      Policy CMP0048 is not set: project() command manages VERSION variables.
      Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
      command to set the policy and suppress this warning.

      The following variable(s) would be set to empty:

        PROJECT_VERSION
        PROJECT_VERSION_MAJOR
    This warning is for project developers.  Use -Wno-dev to suppress it.

    Using Qt5.3.2
    -- Translations: en;pt;nl;es
    -- rpmbuild NOT found. RPM generation will not be available
    -- Found dpkg-deb : /usr/bin/dpkg-deb
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/xxxx/tmp/routerkeygenPC
    make: *** No targets specified and no makefile found.  Stop.
    Error while building

I need to use the command from the INSTALL file
`cc -v && qmake-qt4 -v && cmake -DCMAKE_BUILD_TYPE=Release -DQT_QMAKE_EXECUTABLE=$(which qmake-qt4) && make`
with that command it works fine and I get a executeable file in the bin dir.

**Comment by ruiaraujo** [comment] 2015-02-06 22:36
I will take a look on a Ubuntu system to see if it also fails.

**Comment by hackrid** [comment] 2015-07-13 21:24
any progress here?

**Comment by ruiaraujo** [comment] 2015-09-12 14:00
I am closing this issue since I can't reproduce it.

**Closed by ruiaraujo** 2015-09-12 14:00 UTC

**Comment by TuxCoder** [comment] 2015-09-13 08:31
I have tried it with the current master branch and it works fine, thx for take a look.

Probably create a config file for travis for an automatic build check on a clean system.
If you want I can do that.

**Comment by ruiaraujo** [comment] 2015-09-13 10:15
Feel free to do it and sending in a PR.
